import type { Metadata } from "next";

import "./globals.css";
import { roboto } from "./fonts";
import { ReactNode } from "react";
import { ApolloProviderWrapper } from "@/lib/apollo-provider";
import { AppToastContainer } from "@/components/ui/toast";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`min-h-full flex flex-col ${roboto.variable} ${roboto.className} font-sans antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
          <AppToastContainer />
        </ThemeProvider>
      </body>
    </html>
  );
}
