export const KNOWN_CATEGORIES: Record<string, string[]> = {
  "Programming languages": [
    "TypeScript",
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "C++",
    "C",
  ],
  Frontend: [
    "React",
    "CSS3",
    "SCSS",
    "Storybook",
    "React Query",
    "Redux",
    "Next.js",
    "Vue.js",
    "Angular",
    "HTML5",
    "Tailwind CSS",
    "Webpack",
    "Vite",
  ],
  Backend: [
    "Keycloak",
    "Node.js",
    "NestJS",
    "Express",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "AWS",
  ],
  "Source control systems": ["Git", "GitHub", "GitLab", "Bitbucket", "SVN"],
};

export const DEFAULT_SKILL_CATEGORIES = [
  { id: "cat-prog-lang", name: "Programming languages", order: 1 },
  { id: "cat-frontend", name: "Frontend", order: 2 },
  { id: "cat-backend", name: "Backend", order: 3 },
  { id: "cat-vcs", name: "Source control systems", order: 4 },
  { id: "cat-other", name: "Other", order: 99 },
];
