import * as types from "./graphql";
import type { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

type Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}": typeof types.LoginDocument;
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}": typeof types.UsersDocument;
};
const documents: Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}":
    types.LoginDocument,
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}":
    types.UsersDocument,
};

export function gql(source: string): unknown;

export function gql(
  source: "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}",
): (typeof documents)["mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}"];
export function gql(
  source: "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}",
): (typeof documents)["query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
