/* eslint-disable */
import * as types from "./graphql";
import type { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}": typeof types.LoginDocument;
  "query Cvs($params: SearchPaginationInput) {\n  cvs(params: $params) {\n    items {\n      id\n      created_at\n      name\n      education\n      description\n      user {\n        id\n        email\n        profile {\n          first_name\n          last_name\n          avatar\n        }\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery Cv($cvId: ID!) {\n  cv(cvId: $cvId) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n      profile {\n        first_name\n        last_name\n        avatar\n      }\n    }\n  }\n}\n\nmutation CreateCv($cv: CreateCvInput!) {\n  createCv(cv: $cv) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateCv($cv: UpdateCvInput!) {\n  updateCv(cv: $cv) {\n    id\n    name\n    education\n    description\n  }\n}\n\nmutation DeleteCv($cv: DeleteCvInput!) {\n  deleteCv(cv: $cv) {\n    affected\n  }\n}": typeof types.CvsDocument;
  "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}": typeof types.ProfileLanguagesDocument;
  "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}": typeof types.ProfileSkillsDocument;
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}": typeof types.UsersDocument;
};
const documents: Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}":
    types.LoginDocument,
  "query Cvs($params: SearchPaginationInput) {\n  cvs(params: $params) {\n    items {\n      id\n      created_at\n      name\n      education\n      description\n      user {\n        id\n        email\n        profile {\n          first_name\n          last_name\n          avatar\n        }\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery Cv($cvId: ID!) {\n  cv(cvId: $cvId) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n      profile {\n        first_name\n        last_name\n        avatar\n      }\n    }\n  }\n}\n\nmutation CreateCv($cv: CreateCvInput!) {\n  createCv(cv: $cv) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateCv($cv: UpdateCvInput!) {\n  updateCv(cv: $cv) {\n    id\n    name\n    education\n    description\n  }\n}\n\nmutation DeleteCv($cv: DeleteCvInput!) {\n  deleteCv(cv: $cv) {\n    affected\n  }\n}":
    types.CvsDocument,
  "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}":
    types.ProfileLanguagesDocument,
  "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}":
    types.ProfileSkillsDocument,
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}":
    types.UsersDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(
  source: "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}",
): (typeof documents)["mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(
  source: "query Cvs($params: SearchPaginationInput) {\n  cvs(params: $params) {\n    items {\n      id\n      created_at\n      name\n      education\n      description\n      user {\n        id\n        email\n        profile {\n          first_name\n          last_name\n          avatar\n        }\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery Cv($cvId: ID!) {\n  cv(cvId: $cvId) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n      profile {\n        first_name\n        last_name\n        avatar\n      }\n    }\n  }\n}\n\nmutation CreateCv($cv: CreateCvInput!) {\n  createCv(cv: $cv) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateCv($cv: UpdateCvInput!) {\n  updateCv(cv: $cv) {\n    id\n    name\n    education\n    description\n  }\n}\n\nmutation DeleteCv($cv: DeleteCvInput!) {\n  deleteCv(cv: $cv) {\n    affected\n  }\n}",
): (typeof documents)["query Cvs($params: SearchPaginationInput) {\n  cvs(params: $params) {\n    items {\n      id\n      created_at\n      name\n      education\n      description\n      user {\n        id\n        email\n        profile {\n          first_name\n          last_name\n          avatar\n        }\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery Cv($cvId: ID!) {\n  cv(cvId: $cvId) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n      profile {\n        first_name\n        last_name\n        avatar\n      }\n    }\n  }\n}\n\nmutation CreateCv($cv: CreateCvInput!) {\n  createCv(cv: $cv) {\n    id\n    created_at\n    name\n    education\n    description\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateCv($cv: UpdateCvInput!) {\n  updateCv(cv: $cv) {\n    id\n    name\n    education\n    description\n  }\n}\n\nmutation DeleteCv($cv: DeleteCvInput!) {\n  deleteCv(cv: $cv) {\n    affected\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(
  source: "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}",
): (typeof documents)["query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(
  source: "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}",
): (typeof documents)["query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(
  source: "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}",
): (typeof documents)["query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
