import * as types from "./graphql";
import type { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

type Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}": typeof types.LoginDocument;
  "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}": typeof types.ProfileLanguagesDocument;
  "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}": typeof types.ProfileSkillsDocument;
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}": typeof types.UsersDocument;
};
const documents: Documents = {
  "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}":
    types.LoginDocument,
  "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}":
    types.ProfileLanguagesDocument,
  "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}":
    types.ProfileSkillsDocument,
  "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}":
    types.UsersDocument,
};

export function gql(source: string): unknown;

export function gql(
  source: "mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}",
): (typeof documents)["mutation Login($auth: AuthInput!) {\n  login(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation Signup($auth: SignupInput!) {\n  signup(auth: $auth) {\n    access_token\n    refresh_token\n    user {\n      id\n      email\n    }\n  }\n}\n\nmutation UpdateToken {\n  updateToken {\n    access_token\n    refresh_token\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    role\n    first_name\n    last_name\n    avatar\n  }\n}"];
export function gql(
  source: "query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}",
): (typeof documents)["query ProfileLanguages($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nquery LanguagesCatalog($params: SearchPaginationInput) {\n  languages(params: $params) {\n    items {\n      id\n      name\n      iso2\n      native_name\n    }\n    total\n  }\n}\n\nmutation AddProfileLanguage($language: AddProfileLanguageInput!) {\n  addProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation UpdateProfileLanguage($language: UpdateProfileLanguageInput!) {\n  updateProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}\n\nmutation DeleteProfileLanguage($language: DeleteProfileLanguageInput!) {\n  deleteProfileLanguage(language: $language) {\n    id\n    languages {\n      name\n      proficiency\n    }\n  }\n}"];
export function gql(
  source: "query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}",
): (typeof documents)["query ProfileSkills($userId: ID!) {\n  profile(userId: $userId) {\n    id\n    first_name\n    last_name\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nquery SkillCategories {\n  skillCategories {\n    id\n    name\n    order\n    parent {\n      id\n      name\n    }\n  }\n}\n\nquery SkillsCatalog($params: SearchPaginationInput) {\n  skills(params: $params) {\n    items {\n      id\n      name\n      category {\n        id\n        name\n      }\n    }\n    total\n  }\n}\n\nmutation AddProfileSkill($skill: AddProfileSkillInput!) {\n  addProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation UpdateProfileSkill($skill: UpdateProfileSkillInput!) {\n  updateProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}\n\nmutation DeleteProfileSkill($skill: DeleteProfileSkillInput!) {\n  deleteProfileSkill(skill: $skill) {\n    id\n    skills {\n      name\n      categoryId\n      mastery\n    }\n  }\n}"];
export function gql(
  source: "query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}",
): (typeof documents)["query Users($params: SearchPaginationInput) {\n  users(params: $params) {\n    items {\n      id\n      email\n      profile {\n        id\n        first_name\n        last_name\n        avatar\n      }\n      department {\n        id\n        name\n      }\n      position {\n        id\n        name\n      }\n    }\n    total\n    page\n    limit\n    total_pages\n  }\n}\n\nquery User($userId: ID!) {\n  user(userId: $userId) {\n    id\n    email\n    role\n    created_at\n    profile {\n      id\n      first_name\n      last_name\n      full_name\n      avatar\n    }\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}\n\nquery Departments {\n  departments {\n    items {\n      id\n      name\n    }\n  }\n}\n\nquery Positions {\n  positions {\n    items {\n      id\n      name\n    }\n  }\n}\n\nmutation UpdateProfile($profile: UpdateProfileInput!) {\n  updateProfile(profile: $profile) {\n    id\n    first_name\n    last_name\n  }\n}\n\nmutation UpdateUser($user: UpdateUserInput!) {\n  updateUser(user: $user) {\n    id\n    role\n    department {\n      id\n      name\n    }\n    position {\n      id\n      name\n    }\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
